# Generated by Django 5.2.5 on 2025-08-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('school', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('classLevel', models.CharField(default='Not a Student', max_length=50)),
                ('registrationType', models.CharField(choices=[('Through NGO', 'Through NGO'), ('Through School/College/Institution', 'Through School/College/Institution')], max_length=50)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], max_length=10)),
                ('postalCode', models.CharField(default='250001', max_length=6)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
